### ISSUE TITLE
Destroy a Chart

### ISSUE THREAD

**Issue by bdohmen** [ankane/chartkick.js#56]
What would be the best way to destroy a chart? I add and remove them dynamically and need to mind memory usage.

**Comment by buren** [comment]
You can access any of the charts you have rendered with for example `Chartkick.charts['chart-id-1']`, however setting that to `null` wont do anything. You will have to access the underlying chart library destroy method. @bdohmen Are you using Highcharts or Google Visualization?

**Comment by bdohmen** [comment]
I use Google Visualization.

**Comment by buren** [comment]
Ok, to clear a google visualization chart render with chartkick you can:

```JS
var chartElementId = 'chart-1' // Assuming the chart id is 'chart-1'
var chartkickChart = Chartkick.charts[chartElementId];
.chart.clearChart()
```

**Comment by buren** [comment]
Ok, to clear a google visualization chart render with chartkick you can:

```js
var chartElementId = 'chart-1' // Assuming the chart id is 'chart-1'
var chartkickChart = Chartkick.charts[chartElementId];
var libraryChart = chartkickChart.chart; // In this case it will be a Google Visualization
libraryChart.clearChart(); // clearChart() is a method in the Google Visualization library used for releasing all resources consumed by the chart
```

You can see the method documentation over at [google developers](https://developers.google.com/chart/interactive/docs/gallery/gauge) (scroll down to the "Methods" heading).

@bdohmen hope this helps. In any case I think you could close this issue, since this is clearly not a chartkick issue :)

**Comment by bdohmen** [comment]
Yes you are right. Thanks for your quick help!

**Comment by buren** [comment]
@bdohmen happy to help :)
